from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="BloodGroup", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=80, unique=True)), ("is_active", models.BooleanField(default=True))], options={"ordering": ["name"]}),
        migrations.CreateModel(name="City", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=80, unique=True)), ("is_active", models.BooleanField(default=True))], options={"ordering": ["name"]}),
        migrations.CreateModel(name="District", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=80, unique=True)), ("is_active", models.BooleanField(default=True))], options={"ordering": ["name"]}),
        migrations.CreateModel(name="HealthStatus", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=80, unique=True)), ("is_active", models.BooleanField(default=True))], options={"ordering": ["name"]}),
        migrations.CreateModel(name="OrganType", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=80, unique=True)), ("is_active", models.BooleanField(default=True))], options={"ordering": ["name"]}),
        migrations.CreateModel(name="Donor", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=120)), ("age", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(70)])), ("gender", models.CharField(choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")], max_length=10)), ("mobile_number", models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator("^[0-9]{10}$", "Enter a valid 10 digit mobile number.")])), ("email", models.EmailField(blank=True, max_length=254)), ("address", models.TextField()), ("donor_type", models.CharField(choices=[("Blood", "Blood"), ("Organ", "Organ"), ("Both", "Both")], max_length=10)), ("available", models.BooleanField(default=True)), ("eligibility_status", models.CharField(choices=[("Eligible", "Eligible"), ("Not Eligible", "Not Eligible")], default="Eligible", max_length=20)), ("eligibility_reason", models.CharField(blank=True, max_length=160)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("blood_group", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="donors.bloodgroup")), ("city", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="donors.city")), ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)), ("district", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="donors.district")), ("health_status", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="donors.healthstatus"))], options={"ordering": ["name"]}),
        migrations.CreateModel(name="BloodDonationProfile", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("last_donation_date", models.DateField(blank=True, null=True)), ("medical_fitness_status", models.CharField(choices=[("fit", "Fit"), ("unfit", "Unfit")], default="fit", max_length=10)), ("availability_status", models.CharField(choices=[("available", "Available"), ("unavailable", "Unavailable")], default="available", max_length=12)), ("eligibility_status", models.CharField(default="Eligible", max_length=20)), ("eligibility_reason", models.CharField(blank=True, max_length=160)), ("donor", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="blood_profile", to="donors.donor"))]),
        migrations.CreateModel(name="OrganDonationProfile", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("consent_status", models.BooleanField(default=False)), ("family_contact_name", models.CharField(max_length=120)), ("family_contact_mobile", models.CharField(max_length=10, validators=[django.core.validators.RegexValidator("^[0-9]{10}$", "Enter a valid 10 digit mobile number.")])), ("availability_status", models.CharField(choices=[("available", "Available"), ("unavailable", "Unavailable")], default="available", max_length=12)), ("eligibility_status", models.CharField(default="Eligible", max_length=20)), ("eligibility_reason", models.CharField(blank=True, max_length=160)), ("donor", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="organ_profile", to="donors.donor")), ("organ_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="donors.organtype"))]),
        migrations.CreateModel(name="DonationRequest", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("request_type", models.CharField(choices=[("Blood", "Blood"), ("Organ", "Organ")], max_length=10)), ("hospital_name", models.CharField(max_length=160)), ("contact_person", models.CharField(max_length=120)), ("contact_mobile", models.CharField(max_length=10, validators=[django.core.validators.RegexValidator("^[0-9]{10}$", "Enter a valid 10 digit mobile number.")])), ("emergency", models.BooleanField(default=False)), ("required_date", models.DateField()), ("status", models.CharField(choices=[("Pending", "Pending"), ("Processing", "Processing"), ("Completed", "Completed"), ("Cancelled", "Cancelled")], default="Pending", max_length=12)), ("notes", models.TextField(blank=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("blood_group", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="donors.bloodgroup")), ("city", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="donors.city")), ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)), ("organ_type", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="donors.organtype"))], options={"ordering": ["-emergency", "required_date", "-created_at"]}),
        migrations.AddIndex(model_name="donor", index=models.Index(fields=["blood_group", "city", "eligibility_status"], name="donors_donor_blood_g_915ef2_idx")),
        migrations.AddIndex(model_name="donor", index=models.Index(fields=["donor_type", "eligibility_status"], name="donors_donor_donor_t_67f947_idx")),
    ]
